# Base de datos Railway
spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:59290/railway
spring.datasource.username=root
spring.datasource.password=fyMpLVuUDWpPsUxMYdbHiiOeIZCsEAEi
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Puerto de la app
server.port=8080

# Nombre de la app
spring.application.name=torre-blanca-backend

# JWT
jwt.secret=TorreBlancaSecretKey2024XYZABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklm
jwt.expiration=86400000

# Inicializar contraseñas la primera vez (luego cambiar a false)
app.init-passwords=true